### PR TITLE
Make useEventfulState reactive to obj change

### PR DESCRIPTION
**Pull request by Looooong**

### CODE REVIEW

**Comment by CreepGin** [comment]
I don't think this is necessary. The behavior you are adding is essentially this:
```tsx
useEffect(() => {
    setVal(obj[propertyName])
}, [obj])
```
It should be brought outside of `useEventfulState` to stay inline with existing hooks' patterns. For example, you wouldn't do this:

```tsx
const [count, setCount] = useState(0);
const [foo, setFoo] = useState(count);
```
`foo` will not be updated when count changes. Whatever passed into these hooks should be static initial values. So, just as `useState()` doesn't take in reactive/stateful values, `useEventfulState` shouldn't neither.

**Comment by Looooong** [comment]
> I don't think this is necessary. The behavior you are adding is essentially this:
> 
> ```tsx
> useEffect(() => {
>     setVal(obj[propertyName])
> }, [obj])
> ```

No, it is not the same behaviour. You need to consider the acts of removing the value changed event listener from the old `obj` and add a one to the new `obj`. Without it, there is no way to get value changed notification from the new `obj`. I say this is necessary.

**Comment by jeffomatic** [comment]
I haven't run into this use case myself, but I suspect @Looooong is correct here. If the same callsite to `useEventfulState` passes two different objects across two different render cycles, the remove handler should probably get called in between?

In general, anything you capture in a `useEffect` lambda should be considered a dependency, which includes the event host object (`obj`) in this case.

**Comment by CreepGin** [comment]
Maybe I'm not thinking about the correct use case here. But if both of you deem it necessary, then I'll trust you guys more than me! 😄

**Comment by CreepGin** [comment]
Just want to add a note here. Again, I don't know the use case for mutating the `obj` passed to `useEventfulState`. But if both `obj` and `obj.field` are stateful/mutable, then I do see a potential issue with the `setVal(obj[propertyName])` and `[obj]` combo causing an infinite loop (if you somehow mutate obj based on its field, for example).

**Comment by jeffomatic** [comment]
Hmm I think that’s a good point, and maybe worth reverting until we can
test it out. I didn’t think through the setter function part. To me, it’s
not immediately obvious that you’d want to preserve the same state value
when the host object changes.

**Comment by Looooong** [comment]
I think that would be a case where it is looped deliberately:
```ts
const [a, setA] = useState()
const [b, setB] = useState()

useEffect(() => setA(b), [b])
useEffect(() => setB(a), [a])
```
In my opinion, it is the job of the developer to recognize and prevent chain cyclic update reaction.

**Comment by CreepGin** [comment]
I think it's more about the dependency being hidden inside of a hook. In the above example:

```tsx
const [a, setA] = useState()
const [b, setB] = useState()

// Infinite loop
useEffect(() => setA(b), [b])
useEffect(() => setB(a), [a])
```

The 2 explicit dependency declarations are outside the hook, both apparent to the users. Whereas now this:

```tsx
const [obj, setObj] = useState(...) // I'm assuming obj is being mutated via the useState Hook
const [foo, setFoo] = useEventfulState(obj, "Foo")

// Infinite loop
useEffect(() => setObj(mutatedObj), [foo]) 
```

Only 1 explicit dependency declaration is apparent to the users. The other dep (inside of `useEventfulState`) is hidden from them. This can lead to more confusion when the infinite loop does happen since the user may not be aware of the hidden dependency.

I mentioned this a little bit on Discord. So the reason I was hesitant on this change was because `useEventfulState` was designed to be just like `useState`: accept **static/initial** inputs and produce a stateful/reactive result. And this change disrupts that pattern.

That said, I also recognize the other purpose of `useEventfulState` which is to bridge the C#-JS interop and bring convenience. So I guess I can be okay with it if it does bring in some convenience for an uncommon use case. 👍

**Pull request merged**
