### PR TITLE
Global OneJS host object definition and refactor OneJS hooks

### PR DESCRIPTION
**Pull request by Looooong**
Hooks' type-checking is much shorter and easier to maintain now.

### CODE REVIEW

**Review by CreepGin — CHANGES_REQUESTED** [review]
Noticed a couple things on my side. `tsc` will complain for the following (previously working) usage:

```tsx
interface CharacterManager {
    Health: number

    add_OnHealthChanged(handler: (val: number) => void): void
    remove_OnHealthChanged(handler: (val: number) => void): void
}

...

const [health, setHealth] = useEventfulState(charman, "Health") // <- tsc error here
```

`tsc` complains "Property 'OnHealthChanged' is missing". Ideally we should keep the `add_*` and `remove_*` defs because those are actual callable methods.

The other thing, I'm getting the following error on `onejs/index.ts:99`:

```
Conversion of type 'VisualElement' to type 'T' may be a mistake because neither type sufficiently overlaps with the other.
```

Not sure what's going on there.

**Comment by Looooong** [comment]
Sorry, I didn't add a clear explaination on the new event type definition along with its usage. I mentioned that `TSDefConverter` is modified to add `myEvent: OneJS.Event<() => {}>` along with the `add_` and `remove_` variants. This will be used for type-checking for event name in a type. The updated type definition looks something like this:
```ts
interface CharacterManager {
    Health: number

    add_OnHealthChanged(handler: (val: number) => void): void
    remove_OnHealthChanged(handler: (val: number) => void): void
    OnHealthChanged: OneJS.Event<(val: number) => void>
}
```

`onejs.subscribe` and OneJS's hooks will now only looks for `OneJS.Event<>` properties within a type. The `add_` and `remove_` variants remained for backward compatibility.

So one should regenerate the type definition to get the new event field. It will be a breaking-changes, but only for the definitions.

**Comment by Looooong** [comment]
> The other thing, I'm getting the following error on `onejs/index.ts:99`:
> 
> ```
> Conversion of type 'VisualElement' to type 'T' may be a mistake because neither type sufficiently overlaps with the other.
> ```
> 
> Not sure what's going on there.

I just added a fix for this.

**Comment by CreepGin** [comment]
Nice. All clear on my side now!

**Review by CreepGin — APPROVED** [review]

**Pull request merged**
